// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALcs-xd_0A7XhwLKaLZYdlcqHHhSbqGpo',
    appId: '1:42115618324:android:38bd99f7c8137982b67901',
    messagingSenderId: '42115618324',
    projectId: 'chatty-app-with-getx',
    storageBucket: 'chatty-app-with-getx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD73bjb9V7LHUkQ1a8-s5khYI6Q148F0O4',
    appId: '1:42115618324:ios:a29e6608848a23c0b67901',
    messagingSenderId: '42115618324',
    projectId: 'chatty-app-with-getx',
    storageBucket: 'chatty-app-with-getx.appspot.com',
    androidClientId: '42115618324-2bjhqb7o4mcfaes1to5ludv6v5dq5c3s.apps.googleusercontent.com',
    iosClientId: '42115618324-9uq5v7eon26l01pnsi6s7vtkfp36s2pm.apps.googleusercontent.com',
    iosBundleId: 'com.josephi.chatty',
  );
}
